### ISSUE TITLE
from_analysisplan_map_to_output(): NULL and NA values with repeat variables + errors for different lengths of data and weights

### ISSUE THREAD

**Issue by jprlink** [impact-initiatives/hypegrammaR#6]
**Issue 1: The results for medians and sums calculated with repeat variables (localities and states) are NULL or NA values.

Issue 2: Both with and without repeat variables, rendering of results produces an error like this (for several variables):**

Error in `$<-.data.frame`(`*tmp*`, ".survey.prob.weights", value = c(1.52677597749772,  : 
  replacement has 107 rows, data has 83

Note: I used the hypegrammaR package with added median and sum hypothesis types.

**R code to produce DAP and analysis outputs:**

`################
### Creating DAP

#IMPORTANT: Before loading the file, change collumn header "label::English (en)" in survey and choices tabs of the xls file to "label"

sampling_frame <- read_xlsx("input/sampling_frame_long.xlsx")

survey <- read_excel("input/hh_tool.xls", 1)
choices <- read_excel("input/hh_tool.xls", 2)

data<-matrix(NA,0,length(survey$name[which(!is.na(survey$name))]))
colnames(data)<-survey$name[which(!is.na(survey$name))]
data<-as.data.frame(data)

questionnaire <- koboquest::load_questionnaire(data = data,questions = survey,choices = choices,choices.label.column.to.use ="label")

map_to_datatypes<-function(df,questionnaire){
  
  types <- sapply(names(df),questionnaire$question_type,
                  from.questionnaire = T,
                  from.data = T,
                  data = df)
  
  sm_choices <- purrr::map(names(df),
                           questionnaire$question_is_sm_choice) %>% unlist
  
  raw_q <- questionnaire$raw_questionnaire()$questions
  
  types_raw <- raw_q[match(names(df),raw_q$name),"type"]   
  types[types %in% c("select_one","select_multiple")]<-"categorical"
  types[sm_choices]<-"sm_choice"
  types[types=="numeric"] <- "numerical"
  types[types_raw == "text"] <- "text"
  types[types_raw == "calculate"] <- "numerical"
  
  types
}

make_analysisplan_all_vars <- function(df,
                                       questionnaire,
                                       repeat.for.variable=NA,
                                       independent.variable = NA,
                                       hypothesis.type = "direct_reporting"){
  
  
  if(!is.data.frame(df)){stop(" df must be a data frame")}
  
  types <- map_to_datatypes(df,questionnaire)
  types <- types[!is.na(types)]
  
  if(!is.na(independent.variable)){
    if(any(types[names(types)==independent.variable]!="categorical")){stop("independent variable must be categorical (and can not be select_multiple TRUE/FALSE column")}
    independent.variable.type<-types[names(types)==independent.variable]
  }else{
    independent.variable.type<-NA
  }
  good_dependent_variables<-names(types)[types %in% c("numerical","numeric","categorical")]
  
  analysisplan<-data.frame(research.question = "RQ: not specified (automatic analysisplan)",
                           sub.research.question = "sub RQ not specified (automatic analysisplan)",
                           repeat.for.variable=repeat.for.variable,
                           independent.variable=independent.variable,
                           independent.variable.type=independent.variable.type,
                           dependent.variable=good_dependent_variables,
                           dependent.variable.type = types[good_dependent_variables],
                           hypothesis.type = hypothesis.type,
                           stringsAsFactors = F)
  
}

dap <- make_analysisplan_all_vars(df = data,questionnaire = questionnaire)

clean_vars <- names(hh_data)
clean_vars_df <- as.data.frame(clean_vars) %>% rename("dependent.variable" = "clean_vars")

dap <- dap %>% mutate(independent.variable = "place_holder")

dap <- left_join(clean_vars_df, dap) # add new vars

for (i in c(1:nrow(dap))) {
  if(is.na(dap[i,"independent.variable"])) {
    dap[i,"dependent.variable.type"] <- "numerical"
    }
  if(dap[i,"dependent.variable"] == "rcsi_group" |
     dap[i,"dependent.variable"] == "fcs_group") {
    dap[i,"dependent.variable.type"] <- "categorical"
  }
  if(dap[i,"dependent.variable"] == "fcs" |
     dap[i,"dependent.variable"] == "rcsi") {
    dap[i,"dependent.variable.type"] <- "numerical"
  }
  if(dap[i,"dependent.variable"] == "fcs" |
     dap[i,"dependent.variable"] == "rcsi") {
    dap[i,"dependent.variable.type"] <- "numerical"
  }
}

#view(dap)

dap <- dap[rep(seq_len(nrow(dap)), each = 7), ]

dap$index <- ave(1:nrow(dap), dap$dependent.variable, FUN=seq_along)

for (i in 1:nrow(dap)) {
  if(dap[i,"index"]== 1) {
    dap[i,"repeat.for.variable"] <- NA
    dap[i,"independent.variable"] <- NA
    dap[i,"independent.variable.type"] <- NA
    dap[i,"hypothesis.type"] <- "direct_reporting"
    dap[i,"research.question"] <- "RQ: not specified (automatic analysisplan)"
    dap[i,"sub.research.question"] <- "sub RQ not specified (automatic analysisplan)" 
  }
  if(dap[i,"index"] == 2) {
  dap[i,"repeat.for.variable"] <- "hh_state_label"
  dap[i,"independent.variable"] <- NA
  dap[i,"independent.variable.type"] <- NA
  dap[i,"hypothesis.type"] <- "direct_reporting"
  dap[i,"research.question"] <- "RQ: not specified (automatic analysisplan)"
  dap[i,"sub.research.question"] <- "sub RQ not specified (automatic analysisplan)" 
  }
  if(dap[i,"index"] == 3) {
  dap[i,"repeat.for.variable"] <- "hh_locality_label"
  dap[i,"independent.variable"] <- NA
  dap[i,"independent.variable.type"] <- NA
  dap[i,"hypothesis.type"] <- "direct_reporting"
  dap[i,"research.question"] <- "RQ: not specified (automatic analysisplan)"
  dap[i,"sub.research.question"] <- "sub RQ not specified (automatic analysisplan)" 
  }
  if(dap[i,"index"] == 4) {
  dap[i,"repeat.for.variable"] <- NA
  dap[i,"independent.variable"] <- "displacement_status"
  dap[i,"independent.variable.type"] <- "categorical"
  dap[i,"hypothesis.type"] <- "group_difference"
  dap[i,"research.question"] <- "RQ: not specified (automatic analysisplan)"
  dap[i,"sub.research.question"] <- "sub RQ not specified (automatic analysisplan)" 
  }
  if(dap[i,"index"] == 5) {
    dap[i,"repeat.for.variable"] <- NA
    dap[i,"independent.variable"] <- "hoh_sex"
    dap[i,"independent.variable.type"] <- "categorical"
    dap[i,"hypothesis.type"] <- "group_difference"
    dap[i,"research.question"] <- "RQ: not specified (automatic analysisplan)"
    dap[i,"sub.research.question"] <- "sub RQ not specified (automatic analysisplan)" 
  }
  if(dap[i,"index"] == 6) {
  dap[i,"repeat.for.variable"] <- "hh_state_label"
  dap[i,"independent.variable"] <- "displacement_status"
  dap[i,"independent.variable.type"] <- "categorical"
  dap[i,"hypothesis.type"] <- "group_difference"
  dap[i,"research.question"] <- "RQ: not specified (automatic analysisplan)"
  dap[i,"sub.research.question"] <- "sub RQ not specified (automatic analysisplan)" 
  }
  if(dap[i,"index"] == 7) {
  dap[i,"repeat.for.variable"] <- "hh_locality_label"
  dap[i,"independent.variable"] <- "displacement_status"
  dap[i,"independent.variable.type"] <- "categorical"
  dap[i,"hypothesis.type"] <- "group_difference"
  dap[i,"research.question"] <- "RQ: not specified (automatic analysisplan)"
  dap[i,"sub.research.question"] <- "sub RQ not specified (automatic analysisplan)" 
  }
}

other_vars <- grep("\\_other", names(hh_data), value=TRUE)

other_vars <- other_vars[other_vars != "feedback_mechanism.f2f_aid_worker_other" & 
                           other_vars != "feedback_mechanism.f2f_other" & 
                           other_vars != "hc_dif_type.no_trust_other" & 
                           other_vars != "restriction_type.discrim_other"]

other_vars_binary <- grep("\\.other", names(hh_data), value=TRUE)
vars_binary <- gsub("\\.other", "", other_vars_binary)

drop <- c("start", "end", "today", "survey_type", "consent", "uuid")

drop <- append(vars_binary, drop)

drop <- append(other_vars, drop)

dap <- dap %>% filter(!dependent.variable %in% drop)

ind_names <- read_xlsx("output/dap/dap_sudan_msna_hh_202010.xlsx", 2)
ind_new <- read_xlsx("output/dap/dap_sudan_msna_hh_202010.xlsx", 3)

dap <- left_join(dap, ind_names)
dap <- dap %>%
  mutate(research.question = name)

dap <- dap %>% 
  select(-c(index, name))

dap <- dap %>% 
  filter(!is.na(research.question))

for (i in 1:nrow(dap)) {
  if(grepl("Median", dap[i,"research.question"]) &
     dap[i,"hypothesis.type"] == "group_difference") {
    dap[i,"hypothesis.type"] <- "group_difference_median"
  }
  if(grepl("Median", dap[i,"research.question"]) &
     dap[i,"hypothesis.type"] == "direct_reporting") {
    dap[i,"hypothesis.type"] <- "direct_reporting_median"
  }
  if(grepl("median", dap[i,"research.question"]) &
     dap[i,"hypothesis.type"] == "group_difference") {
    dap[i,"hypothesis.type"] <- "group_difference_median"
  }
  if(grepl("median", dap[i,"research.question"]) &
     dap[i,"hypothesis.type"] == "direct_reporting") {
    dap[i,"hypothesis.type"] <- "direct_reporting_median"
  }
  if(grepl("sum", dap[i,"dependent.variable"]) &
     dap[i,"hypothesis.type"] == "group_difference") {
    dap[i,"hypothesis.type"] <- "group_difference_sum"
  }
  if(grepl("sum", dap[i,"dependent.variable"]) &
     dap[i,"hypothesis.type"] == "direct_reporting") {
    dap[i,"hypothesis.type"] <- "direct_reporting_sum"
  }
}

sum(grepl("sum", dap$dependent.variable))

dap <- dap[which((dap$dependent.variable != dap$independent.variable |
            is.na(dap$independent.variable)) & 
              !is.na(dap$dependent.variable)),]

rownames(dap) <- NULL
view(dap)

#dap_reduced <- dap %>% filter(!dependent.variable %in% ind_new$dependent.variable)
#dap_new_vars <- dap %>% filter(dependent.variable %in% ind_new$dependent.variable)
#rownames(dap_reduced) <- NULL
#rownames(dap_new_vars) <- NULL
#view(dap_reduced)
#view(dap_new_vars)

dap %>% write_xlsx("output/dap/dap_msna_hh.xlsx")

##################
### rendering results

data <- hh_data %>% select(dap$dependent.variable, stratum)

#data <- hh_data %>% select(dap_reduced$dependent.variable, stratum)
#new_data <- hh_data %>% select(dap_new_vars$dependent.variable, stratum)

#data$stratum[!data$stratum %in% sampling_frame$stratum]

# add weights

weights <- map_to_weighting(sampling_frame,
                            data.stratum.column = "stratum",
                            sampling.frame.population.column = "population",
                            sampling.frame.stratum.column = "stratum",
                            data)

#data$weights <- weights(data)

results <- from_analysisplan_map_to_output(data, 
                                           dap, 
                                           weighting = weights)

final_result<- results$results %>%
  lapply(function(x){x$summary.statistic}) %>% do.call(rbind, .)

view(final_result)
names(final_result)
final_result %>% write_xlsx("output/analysis/results_msna_hh_hno_update.xlsx")

# modifying design of analysis output
ind_names <- read_xlsx("output/dap/dap_sudan_msna_hh_202010.xlsx", 2)
ind_names <- ind_names %>% rename(dependent.var = dependent.variable)

final_result <- final_result %>%
  filter(dependent.var != "hh_state_label" &
           dependent.var != "hh_locality_label" &
           dependent.var != "camp_name" &
           dependent.var != "displacement_status")
final_result <- left_join(final_result, ind_names)
final_result <- final_result %>%
  mutate(indicator_description = name)

f_vars <- c("hoh",
            "hc_attempt", 
            "gbv_service_women",
            "gbv_report",
            "hc_pay",
            "hc_dif",
            "erw_awareness",
            "shock_sell",
            "ther_feeding_mic_powd",
            "shock",
            "id_missing",
            "income_challenges",
            "soap",
            "restriction",
            "incident_3m",
            "h_issues",
            "water_problem",
            "source_func",
            "ther_feeding",
            "hh_disability",
            "erw_accident",
            "hh_children_unaccompanied",
            "gbv_areas_avoid",
            "no_info_access",
            "erw_accident_sup",
            "learning_support",
            "school_return",
            "remote_learning",
            "shelter_problem",
            "refugee_card")

f_values <- c("no", "dk", "dwta")
  
final_result <- final_result %>%
  filter(!(dependent.var %in% f_vars & dependent.var.value %in% f_values))

final_result<- final_result %>% 
  select(-name)

final_result <- final_result %>% 
  filter(!(dependent.var %in% c("resp_sex", "hoh_sex") & 
             dependent.var.value %in% "male"))

final_result$indicator_description[final_result$dependent.var == "source"] <- "% of households by type of source of drinking water"

#final_result  <- final_result %>% mutate_at("dependent.var.value", replace_na, replace = "NA")

final_result <- final_result %>%
  rename(indicator_id = dependent.var, response_category = dependent.var.value, result = numbers)

final_result  <- final_result %>% 
  replace_with_na(replace = list(response_category = c("NA", "NULL")))

final_result <- final_result %>% 
  mutate(ind_value_id = paste0(indicator_id, "_", response_category))

for (i in 1:nrow(final_result)) {
  if(!is.na(final_result[i,"response_category"]) &
     final_result[i,"response_category"] != "yes") {
    final_result[i,"indicator_id"] <- final_result[i,"ind_value_id"] 
  }
}

final_result <- final_result %>% 
  filter(indicator_id != "resp_sex")

for (i in 1:nrow(final_result)) {
  if(grepl("%", final_result [i,"indicator_description"])) {
    final_result[i,"result"] <- round(final_result[i,"result"] * 100, digits = 2)
  }
}

ind_names <- final_result %>% 
  select(indicator_id, indicator_description, response_category) %>% distinct()

# national totals 
result_national_totals <- final_result %>%
  filter(is.na(repeat.var) & 
           (is.na(independent.var) | independent.var == "NA"))

result_national_totals <- result_national_totals %>%
  select(indicator_id, indicator_description, result)

result_national_totals <- distinct(result_national_totals)

view(result_national_totals)

result_national_totals %>% write_xlsx("output/analysis/result_national_totals.xlsx")

# national by displacement status
result_national_dis_status <- final_result %>%
  filter(is.na(repeat.var) & 
           independent.var == "displacement_status")

result_national_dis_status <- result_national_dis_status %>%
  select(indicator_id, indicator_description, response_category, result, independent.var.value)

result_national_dis_status_wide <- result_national_dis_status %>% 
  pivot_wider(id_cols = indicator_id, names_from = independent.var.value, values_from = result)

result_national_dis_status_wide <- left_join(result_national_dis_status_wide, ind_names)

result_national_dis_status_wide <- result_national_dis_status_wide %>%
  select(indicator_id, indicator_description, non_displaced, idp, refugee_camp, refugee_non_camp)

result_national_dis_status_wide <- distinct(result_national_dis_status_wide)

view(result_national_dis_status_wide)

result_national_dis_status_wide %>% write_xlsx("output/analysis/result_national_dis_status.xlsx")

# national by HoH sex
result_national_hoh_sex <- final_result %>%
  filter(is.na(repeat.var) & 
           independent.var == "hoh_sex")

result_national_hoh_sex <- result_national_hoh_sex %>%
  select(indicator_id, indicator_description, result, independent.var.value)

result_national_hoh_sex_wide <- result_national_hoh_sex %>% 
  pivot_wider(id_cols = indicator_id, names_from = independent.var.value, values_from = result)

result_national_hoh_sex_wide <- left_join(result_national_hoh_sex_wide, ind_names)

result_national_hoh_sex_wide <- result_national_hoh_sex_wide %>%
  select(indicator_id, indicator_description, female, male)

result_national_hoh_sex_wide <- distinct(result_national_hoh_sex_wide)

view(result_national_hoh_sex_wide)

result_national_hoh_sex_wide %>% write_xlsx("output/analysis/result_national_hoh_sex.xlsx")

# by state
result_states <- final_result %>%
  filter(repeat.var == "hh_state_label" & 
           is.na(independent.var))

result_states <- result_states %>%
  select(indicator_id, indicator_description, result, repeat.var.value)

result_states_wide <- result_states %>% 
  pivot_wider(id_cols = indicator_id, names_from = repeat.var.value, values_from = result)

result_states_wide <- left_join(result_states_wide, ind_names)

result_states_wide <- result_states_wide %>%
  select(indicator_id, indicator_description, c(2:19))

result_states_wide <- distinct(result_states_wide)

view(result_states_wide)

result_states_wide %>% write_xlsx("output/analysis/result_states.xlsx")

# by locality
result_localities <- final_result %>%
  filter(repeat.var == "hh_locality_label" & 
           is.na(independent.var))

result_localities <- result_localities %>%
  select(indicator_id, indicator_description, result, repeat.var.value)

result_localities_wide <- result_localities %>% 
  pivot_wider(id_cols = indicator_id, names_from = repeat.var.value, values_from = result)

result_localities_wide <- left_join(result_localities_wide, ind_names)

result_localities_wide <- result_localities_wide %>%
  select(indicator_id, indicator_description, c(2:122))

result_localities_wide <- distinct(result_localities_wide)

view(result_localities_wide)

result_localities_wide %>% write_xlsx("output/analysis/result_localities.xlsx")`

**Comment by yannsay** [comment]
repeat.var had 2 duplicated names

**Comment by yannsay-impact** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [This is work in Githib](https://trello.com/c/xpbm537N/3-this-is-work-in-githib)
